#!/bin/bash

# This file contains constants for tests

IPLANETDIRECTORYPRO="iPlanetDirectoryPro"
JWT="am-auth-jwt"

ENM_ADMINISTRATOR_USERNAME=administrator   #administratorGAT
ENM_ADMINISTRATOR_PWD=TestPassw0rd   #Gat22.15
ENM_ADMINISTRATOR_COOKIE=./admin_cookie.txt

EXTIDP_PASSWORD=Externalldapadmin01
EXTIDP_REMOTEAUTHN=REMOTEAUTHN
EXTIDP_PROFILE_STANDARD=STANDARD
EXTIDP_PROFILE_NOSEARCH=NOSEARCH
EXTIDP_PROFILE_DEFAULT=${EXTIDP_PROFILE_STANDARD}
EXTIDP_PRIMARY_SERVER="10.45.205.253:1389"
EXTIDP_SECONDARY_SERVER="10.133.245.133:7389"	#141.137.87.62:6389
EXTIDP_BASE_DN="dc=acme,dc=com"
EXTIDP_CONNECTION_MODE=LDAP
EXTIDP_USER_BIND_DN_FORMAT_STANDARD='uid=$user'
EXTIDP_USER_BIND_DN_FORMAT_NOSEARCH='uid=$user,ou=pdu nam,dc=acme,dc=com'
EXTIDP_USER_BIND_DN_FORMAT=${EXTIDP_USER_BIND_DN_FORMAT_STANDARD}
EXTIDP_BIND_DN="cn=extldapadmin,ou=people,dc=acme,dc=com"
EXTIDP_BIND_PASSWORD=Externalldapadmin01

SESSION_ISVALID="valid"
SESSION_ISINVALID="invalid"

SSO_INSTANCE1=sso-instance-1
SSO_INSTANCE2=sso-instance-2


